imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: CHANGEME  # Domain name
secretname: CHANGEME # Cert name value, change this as suited to environment

ingress:
  certIssuerName: CHANGEME # Change this if your certIssuerName has set up different
  whitelistSourceRange: "" # Client based IP if the whitelisting is needed, if not, leave as it is

release_name: "module-byk-training-gui"
  
images:
  gui:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/training-module"
    tag: "CHANGEME" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    tag: "CHANGEME" # Images (tags) are up to date, currently no changes needed
  pipelines:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/training-module"
    tag: "CHANGEME" # Images (tags) are up to date, currently no changes needed
    

env:
  REACT_APP_RUUTER_API_URL: "CHANGEME/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  NODE_ENV: "development"
  CHOKIDAR_USEPOLLING: "true"
  REACT_APP_API_URL: "CHANGEME/v2/private/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
  REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
  REACT_APP_OPENDATAPORT_URL: "https://avaandmed.eesti.ee"
  REACT_APP_RUUTER_V2_PRIVATE_API_URL: "CHANGEME/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "CHANGEME/v2/private/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_URL: "CHANGEME" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_PATH: "/chat/menu.json"
  REACT_APP_AUTH_BASE_URL: "CHANGEME/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_APP_PORT: "3001"
  REACT_APP_LOCAL: "false"
  REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "CHANGEME/et/dev-auth" # Change the domain name, leave subdomain and subpath same
  REACT_APP_CONVERSATIONS_BASE_URL: "CHANGEME/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_TRAINING_BASE_URL: "CHANGEME/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_ANALYTICS_BASE_URL: "CHANGEME/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICES_BASE_URL: "CHANGEME/services" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SETTINGS_BASE_URL: "CHANGEME/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MONITORING_BASE_URL: "CHANGEME/monitoring" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICE_ID: "training"
  REACT_APP_RUUTER_PRIVATE_API_URL: "CHANGEME/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BASE_URL: "byrokratt/"
  REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "CHANGEME/services/" # Change the domain name, leave subdomain and subpath same
  REACT_APP_NODE_ENV: "development"
  REACT_APP_RUUTER_URL: "CHANGEME/v2/private/training/" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_URL: "CHANGEME/v2/private/training/"
  REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "http://module-byk-services-gui:3006"
  REACT_APP_NOTIFICATION_NODE_URL: "CHANGEME"
  REACT_APP_RUUTER_PRIVATE_ENDED_API_URL: "CHANGEME/v2/private/backoffice"

liquibase:
  jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
  dbPassword: "CHANGEME"  # Change password accordingly

resources:
  training:
    requests:
      memory: "100Mi"
      cpu: "1m"
    limits:
      memory: "125Mi"
      cpu: "5m"
  pipeline:
    requests:
      memory: "100Mi"
      cpu: "1m"
    limits:
      memory: "256Mi"
      cpu: "5m"

placeholder:
  ServiceModuleHidden:
  MultiDomainHidden:
